# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('url', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('host', models.TextField()),
                ('title', models.TextField()),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'blogs',
                'managed': False,
            },
        ),
    ]
